import React from "react";
import "../BandQilish/bronQilish.scss";


const Bron = () => {
    return (
        <> 
           <div>
               <h5>Bron page</h5>
               <br />
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
               <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam iure minima delectus officiis dolores aliquid magnam aspernatur aut! Rem labore optio nulla corrupti beatae facere nobis commodi consectetur nihil, vel dolores molestias architecto quis accusamus iusto quaerat molestiae in. Laboriosam nemo eius corporis pariatur. Expedita quia quas ad nam eveniet aut aspernatur quasi veniam laboriosam blanditiis aliquid corporis inventore debitis, incidunt fugit a dicta explicabo eligendi alias totam ratione pariatur dolore molestiae quam. Reiciendis, consectetur voluptatem accusantium ut magni nesciunt corrupti inventore sed dolores officiis minus ea hic ipsa incidunt adipisci laborum facilis dignissimos amet! Eius ex animi vitae quisquam!</p>
           </div>
        </>
    )
}
export default Bron;